### ISSUE TITLE
NetStandard的发布版本和时间有缺误

### ISSUE THREAD

**Issue by nkdanfer** [dotnet-easy/easy-dotnet#4]
net2.1的发布时间是2018年的11月，目前时间轴上的是2019年的11月，见[Announcing .NET Standard 2.1]( https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/)

其余版本见 [.NET Standard](https://learn.microsoft.com/zh-cn/dotnet/standard/net-standard)
及[.NET Standard Versions](https://github.com/dotnet/standard/blob/v2.1.0/docs/versions.md)

**Comment by 786744873** [comment]
![image](https://github.com/dotnet-easy/easy-dotnet/assets/24601648/98301074-bd12-4697-af7b-4140ce36560b)
时间轴上是11月呀
